local o = vim.opt

o.tabstop = 4
o.softtabstop = 4
o.shiftwidth = 4
o.expandtab = true
o.smartindent = true
o.autoindent = true
o.undofile = true
--o.colorcolumn = '80'
o.mouse = 'a'
o.wildmenu = true
o.showmatch = true
o.incsearch = true
o.foldenable = true
o.foldmethod = 'indent'
o.foldlevelstart = 10
o.foldnestmax = 10
o.number = true
o.backspace = 'indent,eol,start'
